site_name: GUV Scale-up Model


# Repository
repo_name: GUV Scale-up Model
repo_url: https://github.com/jamesmulhall/guv-scaleup-model
edit_uri: ""
# Copyright
copyright: James Mulhall

docs_dir: "docs/sources"

plugins:
  - search

theme:
  name: 'readthedocs'
  custom_dir: 'docs'
  palette:
    primary: 'white'
  logo: 'assets/images/logo_full.svg'
  favicon: 'assets/images/favicon.svg'
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - instant
nav:

