name: Docs

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up conda and install from environment.yml
        uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: environment.yml
          activate-environment: guv-scaleup-model
          mamba-version: "*"
      - name: Autogenerate new documentation
        continue-on-error: true
        run: |
          python automate_mkdocs.py
          git add .
      - name: Update and Build GH Pages
        run: gendocs --config mkgendocs.yml
      - name: deploy
        run: mkdocs gh-deploy --force --clean --verbose
      - name: Commit any changes to docs
        continue-on-error: true
        run: |
          git config --local user.name "github-actions[bot]"
          git add ./docs
          git commit -m "Auto-updating the docs"
      - name: Push the changes to master
        continue-on-error: true
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true
